### ISSUE TITLE
Broken url in Quickstart Guid section

### ISSUE THREAD

**Issue by calldata** [tracer-protocol/swaps-client#228]
`tracer-graphs` repo is missing

**Comment by dospore** [comment]
yeah sorry its because tracer-graphs is currently a private repo

**Comment by calldata** [comment]
Ok, i know.  So, if i design my own subgraph, it should be work, right ?

**Comment by dospore** [comment]
But your subgraph would be different to ours. You should be able to use the kovan subgraph in the README
